let seedData = {
  company_values: [
    { value: 'Integrity' },
    { value: 'Initiative' },
    { value: 'Leadership' },
    { value: 'Teamwork' },
    { value: 'Confidence' },
  ],
  users: [
    {
      email: 'gertrude.whiskers@techtonic.com',
      first_name: 'Gertrude',
      last_name: 'Whiskers',
      slack_handle: 'gertrude_winters',
      slack_id: 'CXKJLOKJ4JSHAKD1',
    },
    {
      email: 'robert.smith@techtonic.com',
      first_name: 'Robert',
      last_name: 'Smith',
      slack_handle: 'bob_smith',
      slack_id: 'CXKJLOKJ4JSHAKD2',
    },
    {
      email: 'brian.kerry@techtonic.com',
      first_name: 'Brian',
      last_name: 'Kerry',
      slack_handle: 'brian_kerry',
      slack_id: 'CXKJLOKJ4JSHAKD3',
    },
    {
      email: 'christina.perry@techtonic.com',
      first_name: 'Christina',
      last_name: 'Perry',
      slack_handle: 'chris_perry',
      slack_id: 'CXKJLOKJ4JSHAKD4',
    },
    {
      email: 'eric.bonds@techtonic.com',
      first_name: 'Eric',
      last_name: 'Bonds',
      slack_handle: 'eric_Bonds',
      slack_id: 'CXKJLOKJ4JSHAKD5',
    },
  ],
  shoutouts: [
    {
      date: 'Tues Oct 6 2020',
      message: "Mr. Bundles didn't yell at me today",
      channel_name: 'general',
      shouter: 1,
      shoutee: 2,
      company_value: 2,
    },
    {
      date: 'Wed Oct 7 2020',
      message:
        "Mr. Mackinnon didn't yell at me today. He yelled at me yesterday",
      channel_name: 'general',
      shouter: 4,
      shoutee: 3,
      company_value: 1,
    },
    {
      date: 'Wed Oct 14 2020',
      message: 'Thanks for helping with my ticket!',
      channel_name: 'general',
      shouter: 5,
      shoutee: 4,
      company_value: 4,
    },
    {
      date: 'Fri Oct 16 2020',
      message: 'Thanks for bringing in Donuts',
      channel_name: 'general',
      shouter: 4,
      shoutee: 1,
      company_value: 4,
    },
    {
      date: 'Mon Oct 5 2020',
      message: 'Thanks for bringing in Coffee',
      channel_name: 'general',
      shouter: 3,
      shoutee: 2,
      company_value: 5,
    },
    {
      date: 'Mon Oct 19 2020',
      message: 'For sending everyone pumpkins.',
      channel_name: 'general',
      shouter: 4,
      shoutee: 3,
      company_value: 5,
    },
    {
      date: 'Mon Oct 19 2020',
      message: 'For sending everyone pumpkins.',
      channel_name: 'general',
      shouter: 5,
      shoutee: 3,
      company_value: 5,
    },
    {
      date: 'Mon Oct 19 2020',
      message: 'For helping me with that bug.',
      channel_name: 'general',
      shouter: 1,
      shoutee: 5,
      company_value: 2,
    },
    {
      date: 'Mon Oct 19 2020',
      message: 'Washing the dishes in the breakroom.',
      channel_name: 'general',
      shouter: 2,
      shoutee: 1,
      company_value: 3,
    },
    {
      date: 'Tues Oct 13 2020',
      message: 'Bringing their dog into work.',
      channel_name: 'general',
      shouter: 4,
      shoutee: 2,
      company_value: 1,
    },
    {
      date: "Tues Nov 13 2020",
      message: "Bringing their dog into work.",
      channel_name: "general",
      shouter: 4,
      shoutee: 2,
      company_value: 1,
    },
    {
      date: "Tues Dec 13 2020",
      message: "Bringing their dog into work.",
      channel_name: "general",
      shouter: 4,
      shoutee: 2,
      company_value: 1,
    },
    {
      date: "Tues Dec 13 2019",
      message: "Bringing their dog into work.",
      channel_name: "general",
      shouter: 4,
      shoutee: 2,
      company_value: 1,
    },
  ],
};

module.exports = seedData;
