export const mockShoutData = [
         {
           channel_name: "dev-slack-testing2",
           date: "Fri Oct 16 2020",
           shoutee: {
             email: "elliot.mackinnon@techtonic.com",
             first_name: "elliot",
             last_name: "mackinnon",
             slack_handle: "Elliot Mackinnon",
             user_id: "U01AD22LWCX",
           },
           shouter: {
             email: "travis.gee@techtonic.com",
             first_name: "travis",
             last_name: "gee",
             slack_handle: "Travis",
             user_id: "U01B6CX7L9X",
           },
           shoutout: "For letting us live in his world ",
           values: "Company value number 1",
           shoutId: 1,
         },
         {
           channel_name: "dev-slack-testing2",
           date: "Fri Oct 16 2020",
           shoutee: {
             email: "brian.roxbury@techtonic.com",
             first_name: "brian",
             last_name: "roxbury",
             slack_handle: "Brian Roxbury",
             user_id: "U01B001LJNQ",
           },
           shouter: {
             email: "travis.gee@techtonic.com",
             first_name: "travis",
             last_name: "gee",
             slack_handle: "Travis",
             user_id: "U01B6CX7L9X",
           },
           shoutout: "For making being here today ",
           values: "Company value number 1",
           shoutId: 2,
         },
         {
           channel_name: "dev-slack-testing2",
           date: "Fri Oct 16 2020",
           shoutee: {
             email: "brian.roxbury@techtonic.com",
             first_name: "brian",
             last_name: "roxbury",
             slack_handle: "Brian Roxbury",
             user_id: "U01B001LJNQ",
           },
           shouter: {
             email: "travis.gee@techtonic.com",
             first_name: "travis",
             last_name: "gee",
             slack_handle: "Travis",
             user_id: "U01B6CX7L9X",
           },
           shoutout: "Hi there",
           values: "Company value number 1",
           shoutId: 3,
         },
       ];
